export const USER = "USER";

export const CHANNEL_SET = "CHANNEL-SET";
export const CHANNEL_LIST = "CHANNEL-LIST";
export const CHANNEL_USERS = "CHANNEL-USERS";

/**
 *@Datatype:
 *  CHANNEL_ROUTE_ROOT: Hash
 *  CHANNEL_ROUTE_LOCK: String
 *  CHANNEL_ROUTE_PARENT: Hash
 *  CHANNEL_ROUTE_CHILDREN: Set
 *  CHANNEL_ROUTE_SUBTREE_SIZE: Hash
 */
export const CHANNEL_ROUTE_ROOT = "CHANNEL-ROUTE-ROOT";
export const CHANNEL_ROUTE_LOCK = "CHANNEL-ROUTE-LOCK";
export const CHANNEL_ROUTE_PARENT = "CHANNEL_ROUTE_PARENT";
export const CHANNEL_ROUTE_CHILDREN = "CHANNEL-ROUTE-CHILDREN";
export const CHANNEL_ROUTE_SUBTREE_SIZE = "CHANNEL_ROUTE_SUBTREE_SIZE";
