export const USER = "USER";

/**
 *@Datatype:
 *  CHANNEL_NAME: String
 *  CHANNEL_MEMBERS: Set
 *  CHANNEL_MAP_NAME_ID: Hash
 */
export const CHANNEL_MEMBERS = (_, channelId) => `CHANNEL:${channelId}:MEMBERS`;
export const CHANNEL_NAME = (_, channelId) => `CHANNEL:${channelId}:NAME`;
export const CHANNEL_MAP_NAME_ID = "CHANNEL-MAP-NAME-ID";

/**
 *@Datatype:
 *  CHANNEL_ROUTE_ROOT: Hash
 *  CHANNEL_ROUTE_LOCK: String
 *  CHANNEL_ROUTE_PARENT: Hash
 *  CHANNEL_ROUTE_CHILDREN: Set
 *  CHANNEL_ROUTE_SUBTREE_SIZE: Hash
 */
export const CHANNEL_ROUTE_ROOT = "CHANNEL-ROUTE-ROOT";
export const CHANNEL_ROUTE_LOCK = "CHANNEL-ROUTE-LOCK";
export const CHANNEL_ROUTE_PARENT = "CHANNEL_ROUTE_PARENT";
export const CHANNEL_ROUTE_CHILDREN = "CHANNEL-ROUTE-CHILDREN";
export const CHANNEL_ROUTE_SUBTREE_SIZE = "CHANNEL_ROUTE_SUBTREE_SIZE";
